name: Build with deno

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denoland/setup-deno@main
        with:
          deno-version: "~1.29"
      - name: Run fmt
        run: deno fmt --check
      - name: Run lint
        run: deno lint
      - name: Run check
        run: deno check main.tsx
